### ISSUE TITLE
[Create your first snap] example with tabs fails

### ISSUE THREAD

**Issue by elpuffin** [canonical-web-and-design/tutorials.ubuntu.com#678]
Hi,
In the following snap tutorial:
https://tutorials.ubuntu.com/tutorial/create-your-first-snap#2

The example:

```yaml
parts:
  gnu-hello:
	source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
	plugin: autotools
```
Seems to be malformed and when copied and pasted from the page to a text file, results in an error when running `snapcraft`:

```bash
 snapcraft 
Issues while validating snapcraft.yaml: found character '\t' that cannot start any token on line 12 of snap/snapcraft.yaml
```
I suggest to change it to:

```yaml
parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
    plugin: autotools
``` 
I know you can just type it in and not copy it in, but even if just typed in, it might lead to the error if 
it is typed with the tab and not spaces.

Regards

**Comment by elpuffin** [comment]
It also seems that there are more similar errors in:
https://tutorials.ubuntu.com/tutorial/create-your-first-snap#4
```yaml
parts:
  [...]
  gnu-bash:
	source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
	plugin: autotools
```
which should be:
```yaml
parts:
  [...]
  gnu-bash:
    source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
    plugin: autotools
```

And

```yaml
apps:
  [...]
  bash:
	command: bash
```
should also be:

```yaml
apps:
  [...]
  bash:
    command: bash
```
